### ISSUE TITLE
vbase dont work on win10

### ISSUE THREAD

**Issue by ThunderboltSmile** [sdras/vue-vscode-snippets#25] opened 2018-07-09 07:56 UTC
![image](https://user-images.githubusercontent.com/20284398/42437659-523d0ba8-8390-11e8-898a-f96410d895d5.png)

The first time I typed this command after install this snippet works well, but it only works well once.

**Comment by sdras** [comment] 2018-08-13 16:51
Oh, that's interesting. I'll need to get access to that OS to test, thanks for letting me know.

**Comment by ifkas** [comment] 2018-08-24 19:43
vbase does not work even on my mac either! All other snippets work, only vbase is gone, I reinstalled the extension, I am using latest version of vscode.

**Comment by sdras** [comment] 2018-08-25 03:08
hey @ifkas, are you certain you've created a .vue file before using it? it won't work otherwise (just trying to narrow down possibilities)

**Comment by ifkas** [comment] 2018-08-25 21:59
@sdras you are right!! It was .html file, thank you very much, keep up the good work Sarah, we need people like you in this world :)

**Comment by acmujica** [comment] 2018-10-24 11:52
I'm on Windows 10 and it worked for me.

**Comment by sdras** [comment] 2018-10-24 22:57
I can't reproduce either, I'm going to close this out until we hear from more people that it's a problem.

**Closed by sdras** 2018-10-24 22:57 UTC

**Comment by Failcookie** [comment] 2018-12-28 17:20
I am having the same issue as well on VS Code for Mac. I created a few different new .vue files, but vbase still doesn't work. The Template specific snippets do show up though.

**Comment by chasebank** [comment] 2019-03-12 03:31
Was also experiencing this, somewhat randomly, possibly after some updates. Also Win 10 but I think that's irrelevant.

(for me) It was a settings conflict. I had a number of old json user settings, from my long-running efforts to combat the absolute cluster fk that is the code hover tooltip settings....
-_- 

I had these lines:
```
 "editor.quickSuggestions": {
  "other": false,
   "comments": false,
   "strings": false
 },
"editor.snippetSuggestions": "none",
```
For some reason that doesn't seem to cause issues with tab completes in normal files. But in Vue I wasn't getting any completion outside of `template` tags. There's a Vetur Emmet setting for vue-html files, but I believe that only kicks in inside the template tag, which in our case, before running vbase, dones't exist yet...

At any rate, removing those settings fixed the problem for me.

**Comment by IBM9100** [comment] 2020-04-23 08:13
`"files.associations": {
    "*.art": "html",
    "*.vue": "html",
 }`
I tried removing this code to fix the problem.
