### ISSUE TITLE
The default lang for style is scss. Can I customize it?

### ISSUE THREAD

**Issue by PhilGeng** [sdras/vue-vscode-snippets#54] opened 2019-07-22 09:25 UTC

**Comment by MuBeiSAMA** [comment] 2019-07-26 01:46
see:
Duplicate of #44

**Comment by PhilGeng** [comment] 2019-07-29 06:30
> see #44
Thanks ,I got it.

**Comment by sdras** [comment] 2019-08-16 13:25
closed as duplicate

**Closed by sdras** 2019-08-16 13:25 UTC
